### PR TITLE
Added Support for AnuFonts and ShreeLipi(AVID)

### PR DESCRIPTION
**Pull request by atvKumar**
Added Support for Anu Fonts Windows and Mac

### CODE REVIEW

**Comment by arulalant** [comment]
@arcturusannamalai  It seems worth to merge this pull request. @atvKumar  touched only the necessary  scripts to add new utf8 conversions. What is your view on this ?

**Comment by arcturusannamalai** [comment]
@atvKumar Thanks for your hard work on this. @arulalant I certainly want to merge this code but a few things first,
1. Can we add unittests withh data samples for forward and reverse coveersion?
2. Can we figure out and make all the build pass ?'
3. Please use 'git rebase' to squash the 4 changes to 1 and update this pull request.

It seems to me there is a little bit of polish to be done.

Sincerely
-Muthu

**Comment by atvKumar** [comment]
I tried to squash the commits, but somehow i never see them update in the web, i saw the terminal print out updated. I tried to push... I need to learn more git i guess, really not very well versed in git.

Anyway i tried to merge your changes with mine, i guess its working.

I still need to write the tests and change the authors file.

**Comment by atvKumar** [comment]
The last commit i did, has the necessary unittests. Hope that is enough to merge.

**Comment by arcturusannamalai** [comment]
Thanks Kumaran ( @atvKumar), and for review  @arulalant

**Pull request closed without merging**
